### ISSUE TITLE
Error when I try to compile

### ISSUE THREAD

**Issue by simon88** [johflo/Seeed-Lora-e5#1]
Hi, 
I'm trying to use your projet to test the ping pong projet with Lora E5. When I try to build project I got errors in `/SubGHz_Phy/App/subghz_phy_app.c`

````
../SubGHz_Phy/App/subghz_phy_app.c: In function 'OnTxDone':
../SubGHz_Phy/App/subghz_phy_app.c:125:4: error: 'State' undeclared (first use in this function)
  125 |    State = TX;
      |    ^~~~~
../SubGHz_Phy/App/subghz_phy_app.c:125:4: note: each undeclared identifier is reported only once for each function it appears in
../SubGHz_Phy/App/subghz_phy_app.c:125:12: error: 'TX' undeclared (first use in this function)
  125 |    State = TX;
      |            ^~
../SubGHz_Phy/App/subghz_phy_app.c: In function 'OnRxDone':
../SubGHz_Phy/App/subghz_phy_app.c:138:3: error: 'SnrValue' undeclared (first use in this function)
  138 |   SnrValue = LoraSnr_FskCfo;
      |   ^~~~~~~~
../SubGHz_Phy/App/subghz_phy_app.c:145:3: error: 'State' undeclared (first use in this function)
  145 |   State = RX;
      |   ^~~~~
../SubGHz_Phy/App/subghz_phy_app.c:145:11: error: 'RX' undeclared (first use in this function)
  145 |   State = RX;
      |           ^~
../SubGHz_Phy/App/subghz_phy_app.c:147:10: error: 'BufferRx' undeclared (first use in this function)
  147 |   memset(BufferRx, 0, MAX_APP_BUFFER_SIZE);
      |          ^~~~~~~~
../SubGHz_Phy/App/subghz_phy_app.c:147:23: error: 'MAX_APP_BUFFER_SIZE' undeclared (first use in this function); did you mean 'IS_DMA_BUFFER_SIZE'?
  147 |   memset(BufferRx, 0, MAX_APP_BUFFER_SIZE);
      |                       ^~~~~~~~~~~~~~~~~~~
      |                       IS_DMA_BUFFER_SIZE
../SubGHz_Phy/App/subghz_phy_app.c:149:3: error: 'RxBufferSize' undeclared (first use in this function)
  149 |   RxBufferSize = size;
      |   ^~~~~~~~~~~~
../SubGHz_Phy/App/subghz_phy_app.c:155:3: error: 'RssiValue' undeclared (first use in this function)
  155 |   RssiValue = rssi;
      |   ^~~~~~~~~
../SubGHz_Phy/App/subghz_phy_app.c: In function 'OnTxTimeout':
../SubGHz_Phy/App/subghz_phy_app.c:177:4: error: 'State' undeclared (first use in this function)
  177 |    State = TX_TIMEOUT;
      |    ^~~~~
../SubGHz_Phy/App/subghz_phy_app.c:177:12: error: 'TX_TIMEOUT' undeclared (first use in this function); did you mean 'HAL_TIMEOUT'?
  177 |    State = TX_TIMEOUT;
      |            ^~~~~~~~~~
      |            HAL_TIMEOUT
../SubGHz_Phy/App/subghz_phy_app.c: In function 'OnRxTimeout':
../SubGHz_Phy/App/subghz_phy_app.c:188:4: error: 'State' undeclared (first use in this function)
  188 |    State = RX_TIMEOUT;
      |    ^~~~~
../SubGHz_Phy/App/subghz_phy_app.c:188:12: error: 'RX_TIMEOUT' undeclared (first use in this function); did you mean 'HAL_TIMEOUT'?
  188 |    State = RX_TIMEOUT;
      |            ^~~~~~~~~~
      |            HAL_TIMEOUT
../SubGHz_Phy/App/subghz_phy_app.c: In function 'OnRxError':
../SubGHz_Phy/App/subghz_phy_app.c:199:4: error: 'State' undeclared (first use in this function)
  199 |    State = RX_ERROR;
      |    ^~~~~
../SubGHz_Phy/App/subghz_phy_app.c:199:12: error: 'RX_ERROR' undeclared (first use in this function); did you mean 'HAL_ERROR'?
  199 |    State = RX_ERROR;
      |            ^~~~~~~~
      |            HAL_ERROR
make: *** [SubGHz_Phy/App/subdir.mk:22: SubGHz_Phy/App/subghz_phy_app.o] Error 1
make: *** Waiting for unfinished jobs....
"make -j7 all" terminated with exit code 2. Build might be incomplete.

10:05:07 Build Failed. 17 errors, 0 warnings. (took 1s.507ms)
````

I'm pretty sure the problem is from an incmude path or something like thaht, do you have idea ?

**Comment by johflo** [comment]
Hi
I download the project and import it to teh STM32CubeIDE 1.9.0.
No errors during compilation.

What version do you use? What release of the STM32CubeWL do you use? 1.2, 1.3?

**Comment by simon88** [comment]
Hum this i strange when I launch STM32CubeIde I see on the bottom right v1.8.0 but when Ide is running if I go to Help -> About STM32CubeIDE I got version 1.12.1 and for CubeMX version 6.8.1 and for Stm32CubeWL when I've strat IDE I've seen instalation of version 1.2.0

I have just done a freshly update via Help -> Check for Updates

**Comment by johflo** [comment]
How do you import the project?
The easiest way is to open STM32CubeIDE and double click on the .project file. After the import the build should been working.

**Comment by simon88** [comment]
Perfect it's working thanks

**Comment by simon88** [comment]
I still have the problem if for example I add AES from ioc file and I generate the code when I try to rebuild the project I got the same error as my first message.

If I change nothing I can build the project after import .project file.

Before open ioc file I got a window saying
`This porject was setup with STM32CubeMX V6.6.1 using STM32Cube FW_WL V1.2.0 STM32CubeMX V6.8.1 can work with STM32Cube FW_WL v1.3.0`

After that, I can chosse to stay compatible or to migrate, I stay compatible.

Error seems to come from CubeMX when STM regenerate the code.

Edit : I've tried to migrate to FW 1.3.0 same problem after regenerating the code.

**Comment by simon88** [comment]
EDIT : trick to make it work. Just copy the file `/App/subghz_phy_app.c` before changes, and paste it the folder after regenerate the new code. I dont know why, but when IDE regenerate the code all the `/App/subghz_phy_app.c` are replace and we loose all Private variables and functions content.

**Comment by johflo** [comment]
Thats normal. If you make changes with the CubeMX, STM32CubeIDE wil regenerate the project with the "original" firmware files.
Because of this I used the files from https://github.com/danak6jq/Seeed-LoRa-E5, but this works only with the 1.2 firmware.

**Comment by simon88** [comment]
Ok thanks I understand @johflo, just a question it's not possible to replace original firmware with files for lora e5 module ? 

If I’m right, the only changes between original firmware and Lora e5 firmware are pin definition like RF_CTRL1 ?

**Comment by johflo** [comment]
Hi, there are some changes too like HP and LP transmission.
Take a look at https://github.com/danak6jq/Seeed-LoRa-E5 .
There you can find the 1.3 firmware for the lora E5
